# Generated by Django 3.2.7 on 2021-10-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocompare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='market_cap',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='crypto',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
