# Generated by Django 3.2.7 on 2021-10-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocompare', '0002_auto_20211002_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='market_cap',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='volume',
            field=models.FloatField(default=0),
        ),
    ]
