# Generated by Django 3.2.7 on 2021-10-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocompare', '0003_auto_20211002_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='percent_change',
        ),
        migrations.AlterField(
            model_name='crypto',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
