# Generated by Django 3.2.7 on 2021-10-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocompare', '0004_auto_20211002_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='crypto_price_one',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='crypto',
            name='crypto_price_two',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='crypto',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
