# Generated by Django 3.2.7 on 2021-10-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocompare', '0006_auto_20211003_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crypto',
            options={'verbose_name_plural': 'Crypto'},
        ),
    ]
