# Generated by Django 3.2.7 on 2021-10-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocompare', '0007_alter_crypto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='ticker',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
