# Generated by Django 3.2.2 on 2021-10-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocompare', '0012_auto_20211019_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='crypto',
        ),
        migrations.AddField(
            model_name='news',
            name='crypto',
            field=models.ManyToManyField(related_name='news', to='cryptocompare.Crypto'),
        ),
    ]
