# Generated by Django 3.2.2 on 2021-10-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocompare', '0014_alter_news_crypto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='crypto',
            field=models.ManyToManyField(related_name='crypto', to='cryptocompare.Crypto'),
        ),
    ]
