# Generated by Django 3.2.2 on 2021-10-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocompare', '0015_alter_news_crypto'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='close_price',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='crypto',
            name='high_price',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='crypto',
            name='low_price',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
    ]
