# Generated by Django 3.2.2 on 2021-10-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocompare', '0016_auto_20211020_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='base_currency',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='quote_currency',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
