# Generated by Django 3.2.2 on 2021-10-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocompare', '0018_auto_20211022_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='current_price',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='high_price',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='low_price',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
