# Generated by Django 3.2.2 on 2021-10-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocompare', '0019_auto_20211022_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
