# Generated by Django 3.2.2 on 2021-10-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocompare', '0021_rename_coin_name_portfolio_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='name',
            new_name='coin_name',
        ),
    ]
