# Generated by Django 3.2.2 on 2021-10-24 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocompare', '0022_rename_name_portfolio_coin_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=10, null=True)),
                ('current_price', models.DecimalField(decimal_places=20, default=0, max_digits=40)),
                ('volume', models.IntegerField(default=0)),
                ('high_price', models.DecimalField(decimal_places=20, default=0, max_digits=40)),
                ('low_price', models.DecimalField(decimal_places=20, default=0, max_digits=40)),
            ],
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='coin_name',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='cryptocompare.crypto'),
        ),
    ]
