# Generated by Django 3.2.2 on 2021-10-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocompare', '0023_auto_20211024_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='low_price',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='ticker',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='volume',
        ),
    ]
