# Generated by Django 3.2.2 on 2021-10-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocompare', '0025_auto_20211024_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='current_price',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='high_price',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='low_price',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='ticker',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='coin_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Cryptocurrency',
        ),
    ]
