# Generated by Django 3.2.2 on 2021-10-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocompare', '0026_auto_20211024_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image_url',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='ticker',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
